// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: proto/rserve.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RServe_RunTask_FullMethodName   = "/rserve.RServe/RunTask"
	RServe_RunBundle_FullMethodName = "/rserve.RServe/RunBundle"
	RServe_ListTasks_FullMethodName = "/rserve.RServe/ListTasks"
	RServe_GetStatus_FullMethodName = "/rserve.RServe/GetStatus"
	RServe_CancelRun_FullMethodName = "/rserve.RServe/CancelRun"
)

// RServeClient is the client API for RServe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RServeClient interface {
	// Run a single tool task (rclaude, rcodex, rgemini), stream events back
	RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	// Run a bundle (orchestrated multi-step workflow), stream events back
	RunBundle(ctx context.Context, in *RunBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	// List available task shortcuts and bundles
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Get server status (health, active runs)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Cancel a running task by run ID
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
}

type rServeClient struct {
	cc grpc.ClientConnInterface
}

func NewRServeClient(cc grpc.ClientConnInterface) RServeClient {
	return &rServeClient{cc}
}

func (c *rServeClient) RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RServe_ServiceDesc.Streams[0], RServe_RunTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunTaskRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RServe_RunTaskClient = grpc.ServerStreamingClient[RunEvent]

func (c *rServeClient) RunBundle(ctx context.Context, in *RunBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RServe_ServiceDesc.Streams[1], RServe_RunBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunBundleRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RServe_RunBundleClient = grpc.ServerStreamingClient[RunEvent]

func (c *rServeClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, RServe_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rServeClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, RServe_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rServeClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, RServe_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RServeServer is the server API for RServe service.
// All implementations must embed UnimplementedRServeServer
// for forward compatibility.
type RServeServer interface {
	// Run a single tool task (rclaude, rcodex, rgemini), stream events back
	RunTask(*RunTaskRequest, grpc.ServerStreamingServer[RunEvent]) error
	// Run a bundle (orchestrated multi-step workflow), stream events back
	RunBundle(*RunBundleRequest, grpc.ServerStreamingServer[RunEvent]) error
	// List available task shortcuts and bundles
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Get server status (health, active runs)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Cancel a running task by run ID
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	mustEmbedUnimplementedRServeServer()
}

// UnimplementedRServeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRServeServer struct{}

func (UnimplementedRServeServer) RunTask(*RunTaskRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedRServeServer) RunBundle(*RunBundleRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method RunBundle not implemented")
}
func (UnimplementedRServeServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedRServeServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRServeServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedRServeServer) mustEmbedUnimplementedRServeServer() {}
func (UnimplementedRServeServer) testEmbeddedByValue()                {}

// UnsafeRServeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RServeServer will
// result in compilation errors.
type UnsafeRServeServer interface {
	mustEmbedUnimplementedRServeServer()
}

func RegisterRServeServer(s grpc.ServiceRegistrar, srv RServeServer) {
	// If the following call panics, it indicates UnimplementedRServeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RServe_ServiceDesc, srv)
}

func _RServe_RunTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RServeServer).RunTask(m, &grpc.GenericServerStream[RunTaskRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RServe_RunTaskServer = grpc.ServerStreamingServer[RunEvent]

func _RServe_RunBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunBundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RServeServer).RunBundle(m, &grpc.GenericServerStream[RunBundleRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RServe_RunBundleServer = grpc.ServerStreamingServer[RunEvent]

func _RServe_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RServeServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RServe_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RServeServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RServe_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RServeServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RServe_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RServeServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RServe_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RServeServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RServe_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RServeServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RServe_ServiceDesc is the grpc.ServiceDesc for RServe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RServe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rserve.RServe",
	HandlerType: (*RServeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _RServe_ListTasks_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RServe_GetStatus_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _RServe_CancelRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTask",
			Handler:       _RServe_RunTask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunBundle",
			Handler:       _RServe_RunBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rserve.proto",
}
