// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/rserve.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`                                                                                     // "claude", "codex", "gemini"
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`                                                                                     // Task text or shortcut name
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                                                                   // Model override (optional)
	MaxBudget     string                 `protobuf:"bytes,4,opt,name=max_budget,json=maxBudget,proto3" json:"max_budget,omitempty"`                                                          // Budget in USD (optional)
	WorkDirs      []string               `protobuf:"bytes,5,rep,name=work_dirs,json=workDirs,proto3" json:"work_dirs,omitempty"`                                                             // Target directories
	Variables     map[string]string      `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Template variables (-x key=val)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_proto_rserve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{0}
}

func (x *RunTaskRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *RunTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *RunTaskRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunTaskRequest) GetMaxBudget() string {
	if x != nil {
		return x.MaxBudget
	}
	return ""
}

func (x *RunTaskRequest) GetWorkDirs() []string {
	if x != nil {
		return x.WorkDirs
	}
	return nil
}

func (x *RunTaskRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type RunBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        string                 `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`                                                                           // Bundle name
	Inputs        map[string]string      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Bundle inputs
	OpusOnly      bool                   `protobuf:"varint,3,opt,name=opus_only,json=opusOnly,proto3" json:"opus_only,omitempty"`
	FlashOnly     bool                   `protobuf:"varint,4,opt,name=flash_only,json=flashOnly,proto3" json:"flash_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunBundleRequest) Reset() {
	*x = RunBundleRequest{}
	mi := &file_proto_rserve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBundleRequest) ProtoMessage() {}

func (x *RunBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBundleRequest.ProtoReflect.Descriptor instead.
func (*RunBundleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{1}
}

func (x *RunBundleRequest) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

func (x *RunBundleRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RunBundleRequest) GetOpusOnly() bool {
	if x != nil {
		return x.OpusOnly
	}
	return false
}

func (x *RunBundleRequest) GetFlashOnly() bool {
	if x != nil {
		return x.FlashOnly
	}
	return false
}

type RunEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RunId       string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunEvent_Init
	//	*RunEvent_Text
	//	*RunEvent_ToolUse
	//	*RunEvent_StepProgress
	//	*RunEvent_Result
	//	*RunEvent_Error
	Event         isRunEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_proto_rserve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{2}
}

func (x *RunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RunEvent) GetEvent() isRunEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunEvent) GetInit() *InitEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *RunEvent) GetText() *TextEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *RunEvent) GetToolUse() *ToolUseEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_ToolUse); ok {
			return x.ToolUse
		}
	}
	return nil
}

func (x *RunEvent) GetStepProgress() *StepProgressEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_StepProgress); ok {
			return x.StepProgress
		}
	}
	return nil
}

func (x *RunEvent) GetResult() *ResultEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *RunEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRunEvent_Event interface {
	isRunEvent_Event()
}

type RunEvent_Init struct {
	Init *InitEvent `protobuf:"bytes,3,opt,name=init,proto3,oneof"`
}

type RunEvent_Text struct {
	Text *TextEvent `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type RunEvent_ToolUse struct {
	ToolUse *ToolUseEvent `protobuf:"bytes,5,opt,name=tool_use,json=toolUse,proto3,oneof"`
}

type RunEvent_StepProgress struct {
	StepProgress *StepProgressEvent `protobuf:"bytes,6,opt,name=step_progress,json=stepProgress,proto3,oneof"`
}

type RunEvent_Result struct {
	Result *ResultEvent `protobuf:"bytes,7,opt,name=result,proto3,oneof"`
}

type RunEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

func (*RunEvent_Init) isRunEvent_Event() {}

func (*RunEvent_Text) isRunEvent_Event() {}

func (*RunEvent_ToolUse) isRunEvent_Event() {}

func (*RunEvent_StepProgress) isRunEvent_Event() {}

func (*RunEvent_Result) isRunEvent_Event() {}

func (*RunEvent_Error) isRunEvent_Event() {}

type InitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEvent) Reset() {
	*x = InitEvent{}
	mi := &file_proto_rserve_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEvent) ProtoMessage() {}

func (x *InitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEvent.ProtoReflect.Descriptor instead.
func (*InitEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{3}
}

func (x *InitEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *InitEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type TextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEvent) Reset() {
	*x = TextEvent{}
	mi := &file_proto_rserve_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEvent) ProtoMessage() {}

func (x *TextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEvent.ProtoReflect.Descriptor instead.
func (*TextEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{4}
}

func (x *TextEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToolUseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"` // "Read", "Write", "Bash", etc.
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`                   // Formatted summary (file path, command, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUseEvent) Reset() {
	*x = ToolUseEvent{}
	mi := &file_proto_rserve_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUseEvent) ProtoMessage() {}

func (x *ToolUseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUseEvent.ProtoReflect.Descriptor instead.
func (*ToolUseEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{5}
}

func (x *ToolUseEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolUseEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type StepProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "completed", "skipped", "failed"
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,5,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Tokens        int32                  `protobuf:"varint,7,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepProgressEvent) Reset() {
	*x = StepProgressEvent{}
	mi := &file_proto_rserve_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepProgressEvent) ProtoMessage() {}

func (x *StepProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepProgressEvent.ProtoReflect.Descriptor instead.
func (*StepProgressEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{6}
}

func (x *StepProgressEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepProgressEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepProgressEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *StepProgressEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StepProgressEvent) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *StepProgressEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepProgressEvent) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type ResultEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // Final result text
	Usage         *TokenUsage            `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	TotalCostUsd  float64                `protobuf:"fixed64,4,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	Grade         string                 `protobuf:"bytes,5,opt,name=grade,proto3" json:"grade,omitempty"` // Extracted grade if present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultEvent) Reset() {
	*x = ResultEvent{}
	mi := &file_proto_rserve_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEvent) ProtoMessage() {}

func (x *ResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEvent.ProtoReflect.Descriptor instead.
func (*ResultEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{7}
}

func (x *ResultEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ResultEvent) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ResultEvent) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ResultEvent) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

func (x *ResultEvent) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_rserve_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TokenUsage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InputTokens         int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens        int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens     int32                  `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheCreationTokens int32                  `protobuf:"varint,4,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_proto_rserve_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{9}
}

func (x *TokenUsage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetCacheReadTokens() int32 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *TokenUsage) GetCacheCreationTokens() int32 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_rserve_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{10}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Bundles       []*BundleInfo          `protobuf:"bytes,2,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_rserve_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetBundles() []*BundleInfo {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_proto_rserve_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{12}
}

func (x *TaskInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskInfo) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

type BundleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StepCount     int32                  `protobuf:"varint,3,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleInfo) Reset() {
	*x = BundleInfo{}
	mi := &file_proto_rserve_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleInfo) ProtoMessage() {}

func (x *BundleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleInfo.ProtoReflect.Descriptor instead.
func (*BundleInfo) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{13}
}

func (x *BundleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BundleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BundleInfo) GetStepCount() int32 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_rserve_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{14}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ActiveRuns    int32                  `protobuf:"varint,2,opt,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Runs          []*ActiveRun           `protobuf:"bytes,4,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_rserve_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetActiveRuns() int32 {
	if x != nil {
		return x.ActiveRuns
	}
	return 0
}

func (x *GetStatusResponse) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *GetStatusResponse) GetRuns() []*ActiveRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

type ActiveRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	StartedAtMs   int64                  `protobuf:"varint,4,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveRun) Reset() {
	*x = ActiveRun{}
	mi := &file_proto_rserve_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRun) ProtoMessage() {}

func (x *ActiveRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRun.ProtoReflect.Descriptor instead.
func (*ActiveRun) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{16}
}

func (x *ActiveRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ActiveRun) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ActiveRun) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *ActiveRun) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_proto_rserve_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{17}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_proto_rserve_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rserve_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_rserve_proto_rawDescGZIP(), []int{18}
}

func (x *CancelRunResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_rserve_proto protoreflect.FileDescriptor

const file_proto_rserve_proto_rawDesc = "" +
	"\n" +
	"\x12proto/rserve.proto\x12\x06rserve\"\x8d\x02\n" +
	"\x0eRunTaskRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_budget\x18\x04 \x01(\tR\tmaxBudget\x12\x1b\n" +
	"\twork_dirs\x18\x05 \x03(\tR\bworkDirs\x12C\n" +
	"\tvariables\x18\x06 \x03(\v2%.rserve.RunTaskRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x01\n" +
	"\x10RunBundleRequest\x12\x16\n" +
	"\x06bundle\x18\x01 \x01(\tR\x06bundle\x12<\n" +
	"\x06inputs\x18\x02 \x03(\v2$.rserve.RunBundleRequest.InputsEntryR\x06inputs\x12\x1b\n" +
	"\topus_only\x18\x03 \x01(\bR\bopusOnly\x12\x1d\n" +
	"\n" +
	"flash_only\x18\x04 \x01(\bR\tflashOnly\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x02\n" +
	"\bRunEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12'\n" +
	"\x04init\x18\x03 \x01(\v2\x11.rserve.InitEventH\x00R\x04init\x12'\n" +
	"\x04text\x18\x04 \x01(\v2\x11.rserve.TextEventH\x00R\x04text\x121\n" +
	"\btool_use\x18\x05 \x01(\v2\x14.rserve.ToolUseEventH\x00R\atoolUse\x12@\n" +
	"\rstep_progress\x18\x06 \x01(\v2\x19.rserve.StepProgressEventH\x00R\fstepProgress\x12-\n" +
	"\x06result\x18\a \x01(\v2\x13.rserve.ResultEventH\x00R\x06result\x12*\n" +
	"\x05error\x18\b \x01(\v2\x12.rserve.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"T\n" +
	"\tInitEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"%\n" +
	"\tTextEvent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"E\n" +
	"\fToolUseEvent\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"\xc6\x01\n" +
	"\x11StepProgressEvent\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x19\n" +
	"\bcost_usd\x18\x05 \x01(\x01R\acostUsd\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06tokens\x18\a \x01(\x05R\x06tokens\"\xa8\x01\n" +
	"\vResultEvent\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12(\n" +
	"\x05usage\x18\x03 \x01(\v2\x12.rserve.TokenUsageR\x05usage\x12$\n" +
	"\x0etotal_cost_usd\x18\x04 \x01(\x01R\ftotalCostUsd\x12\x14\n" +
	"\x05grade\x18\x05 \x01(\tR\x05grade\":\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xb4\x01\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x05R\x0fcacheReadTokens\x122\n" +
	"\x15cache_creation_tokens\x18\x04 \x01(\x05R\x13cacheCreationTokens\"\x12\n" +
	"\x10ListTasksRequest\"i\n" +
	"\x11ListTasksResponse\x12&\n" +
	"\x05tasks\x18\x01 \x03(\v2\x10.rserve.TaskInfoR\x05tasks\x12,\n" +
	"\abundles\x18\x02 \x03(\v2\x12.rserve.BundleInfoR\abundles\"T\n" +
	"\bTaskInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\"a\n" +
	"\n" +
	"BundleInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"step_count\x18\x03 \x01(\x05R\tstepCount\"\x12\n" +
	"\x10GetStatusRequest\"\x9c\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vactive_runs\x18\x02 \x01(\x05R\n" +
	"activeRuns\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\x12%\n" +
	"\x04runs\x18\x04 \x03(\v2\x11.rserve.ActiveRunR\x04runs\"n\n" +
	"\tActiveRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12\"\n" +
	"\rstarted_at_ms\x18\x04 \x01(\x03R\vstartedAtMs\")\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"K\n" +
	"\x11CancelRunResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc0\x02\n" +
	"\x06RServe\x125\n" +
	"\aRunTask\x12\x16.rserve.RunTaskRequest\x1a\x10.rserve.RunEvent0\x01\x129\n" +
	"\tRunBundle\x12\x18.rserve.RunBundleRequest\x1a\x10.rserve.RunEvent0\x01\x12@\n" +
	"\tListTasks\x12\x18.rserve.ListTasksRequest\x1a\x19.rserve.ListTasksResponse\x12@\n" +
	"\tGetStatus\x12\x18.rserve.GetStatusRequest\x1a\x19.rserve.GetStatusResponse\x12@\n" +
	"\tCancelRun\x12\x18.rserve.CancelRunRequest\x1a\x19.rserve.CancelRunResponseB\x18Z\x16rcodegen/pkg/server/pbb\x06proto3"

var (
	file_proto_rserve_proto_rawDescOnce sync.Once
	file_proto_rserve_proto_rawDescData []byte
)

func file_proto_rserve_proto_rawDescGZIP() []byte {
	file_proto_rserve_proto_rawDescOnce.Do(func() {
		file_proto_rserve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rserve_proto_rawDesc), len(file_proto_rserve_proto_rawDesc)))
	})
	return file_proto_rserve_proto_rawDescData
}

var file_proto_rserve_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_rserve_proto_goTypes = []any{
	(*RunTaskRequest)(nil),    // 0: rserve.RunTaskRequest
	(*RunBundleRequest)(nil),  // 1: rserve.RunBundleRequest
	(*RunEvent)(nil),          // 2: rserve.RunEvent
	(*InitEvent)(nil),         // 3: rserve.InitEvent
	(*TextEvent)(nil),         // 4: rserve.TextEvent
	(*ToolUseEvent)(nil),      // 5: rserve.ToolUseEvent
	(*StepProgressEvent)(nil), // 6: rserve.StepProgressEvent
	(*ResultEvent)(nil),       // 7: rserve.ResultEvent
	(*ErrorEvent)(nil),        // 8: rserve.ErrorEvent
	(*TokenUsage)(nil),        // 9: rserve.TokenUsage
	(*ListTasksRequest)(nil),  // 10: rserve.ListTasksRequest
	(*ListTasksResponse)(nil), // 11: rserve.ListTasksResponse
	(*TaskInfo)(nil),          // 12: rserve.TaskInfo
	(*BundleInfo)(nil),        // 13: rserve.BundleInfo
	(*GetStatusRequest)(nil),  // 14: rserve.GetStatusRequest
	(*GetStatusResponse)(nil), // 15: rserve.GetStatusResponse
	(*ActiveRun)(nil),         // 16: rserve.ActiveRun
	(*CancelRunRequest)(nil),  // 17: rserve.CancelRunRequest
	(*CancelRunResponse)(nil), // 18: rserve.CancelRunResponse
	nil,                       // 19: rserve.RunTaskRequest.VariablesEntry
	nil,                       // 20: rserve.RunBundleRequest.InputsEntry
}
var file_proto_rserve_proto_depIdxs = []int32{
	19, // 0: rserve.RunTaskRequest.variables:type_name -> rserve.RunTaskRequest.VariablesEntry
	20, // 1: rserve.RunBundleRequest.inputs:type_name -> rserve.RunBundleRequest.InputsEntry
	3,  // 2: rserve.RunEvent.init:type_name -> rserve.InitEvent
	4,  // 3: rserve.RunEvent.text:type_name -> rserve.TextEvent
	5,  // 4: rserve.RunEvent.tool_use:type_name -> rserve.ToolUseEvent
	6,  // 5: rserve.RunEvent.step_progress:type_name -> rserve.StepProgressEvent
	7,  // 6: rserve.RunEvent.result:type_name -> rserve.ResultEvent
	8,  // 7: rserve.RunEvent.error:type_name -> rserve.ErrorEvent
	9,  // 8: rserve.ResultEvent.usage:type_name -> rserve.TokenUsage
	12, // 9: rserve.ListTasksResponse.tasks:type_name -> rserve.TaskInfo
	13, // 10: rserve.ListTasksResponse.bundles:type_name -> rserve.BundleInfo
	16, // 11: rserve.GetStatusResponse.runs:type_name -> rserve.ActiveRun
	0,  // 12: rserve.RServe.RunTask:input_type -> rserve.RunTaskRequest
	1,  // 13: rserve.RServe.RunBundle:input_type -> rserve.RunBundleRequest
	10, // 14: rserve.RServe.ListTasks:input_type -> rserve.ListTasksRequest
	14, // 15: rserve.RServe.GetStatus:input_type -> rserve.GetStatusRequest
	17, // 16: rserve.RServe.CancelRun:input_type -> rserve.CancelRunRequest
	2,  // 17: rserve.RServe.RunTask:output_type -> rserve.RunEvent
	2,  // 18: rserve.RServe.RunBundle:output_type -> rserve.RunEvent
	11, // 19: rserve.RServe.ListTasks:output_type -> rserve.ListTasksResponse
	15, // 20: rserve.RServe.GetStatus:output_type -> rserve.GetStatusResponse
	18, // 21: rserve.RServe.CancelRun:output_type -> rserve.CancelRunResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_rserve_proto_init() }
func file_proto_rserve_proto_init() {
	if File_proto_rserve_proto != nil {
		return
	}
	file_proto_rserve_proto_msgTypes[2].OneofWrappers = []any{
		(*RunEvent_Init)(nil),
		(*RunEvent_Text)(nil),
		(*RunEvent_ToolUse)(nil),
		(*RunEvent_StepProgress)(nil),
		(*RunEvent_Result)(nil),
		(*RunEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rserve_proto_rawDesc), len(file_proto_rserve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rserve_proto_goTypes,
		DependencyIndexes: file_proto_rserve_proto_depIdxs,
		MessageInfos:      file_proto_rserve_proto_msgTypes,
	}.Build()
	File_proto_rserve_proto = out.File
	file_proto_rserve_proto_goTypes = nil
	file_proto_rserve_proto_depIdxs = nil
}
